name: slinky
description: A simple web-crawler
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.5.0
  html: ^0.15.0
  http_status: ^3.3.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
